//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Imkery.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Imkery.Client.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        internal static string Dashboard_Title {
            get {
                return ResourceManager.GetString("Dashboard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imkery.
        /// </summary>
        internal static string Global_Imkery {
            get {
                return ResourceManager.GetString("Global_Imkery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Global_LoadingPlaceholder {
            get {
                return ResourceManager.GetString("Global_LoadingPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        internal static string Global_NoDataFoundPlaceholder {
            get {
                return ResourceManager.GetString("Global_NoDataFoundPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Global_NotFoundPlaceholder {
            get {
                return ResourceManager.GetString("Global_NotFoundPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s nothing at this address....
        /// </summary>
        internal static string Global_NothingHerePlaceholder {
            get {
                return ResourceManager.GetString("Global_NothingHerePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Global_SaveAction {
            get {
                return ResourceManager.GetString("Global_SaveAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        internal static string Global_SearchPlaceholder {
            get {
                return ResourceManager.GetString("Global_SearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Global_SelectAction {
            get {
                return ResourceManager.GetString("Global_SelectAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource..
        /// </summary>
        internal static string Global_UnauthorizedPlaceholder {
            get {
                return ResourceManager.GetString("Global_UnauthorizedPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hive # {0}.
        /// </summary>
        internal static string HiveCard_HiveIdentifierFormat {
            get {
                return ResourceManager.GetString("HiveCard_HiveIdentifierFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string HiveEntity_Identifier {
            get {
                return ResourceManager.GetString("HiveEntity_Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add hive.
        /// </summary>
        internal static string HivesOverview_AddHives {
            get {
                return ResourceManager.GetString("HivesOverview_AddHives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hives overview.
        /// </summary>
        internal static string HivesOverview_Title {
            get {
                return ResourceManager.GetString("HivesOverview_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Imkery!.
        /// </summary>
        internal static string Index_WelcomeMessage {
            get {
                return ResourceManager.GetString("Index_WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string LocationEntity_City {
            get {
                return ResourceManager.GetString("LocationEntity_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string LocationEntity_Name {
            get {
                return ResourceManager.GetString("LocationEntity_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string LocationEntity_Street {
            get {
                return ResourceManager.GetString("LocationEntity_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This site is under heavy development, visit the github for updates..
        /// </summary>
        internal static string MainLayout_MaintenanceMessage {
            get {
                return ResourceManager.GetString("MainLayout_MaintenanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string NavMenu_LogOut {
            get {
                return ResourceManager.GetString("NavMenu_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string NavMenu_Register {
            get {
                return ResourceManager.GetString("NavMenu_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string NavMenu_SignIn {
            get {
                return ResourceManager.GetString("NavMenu_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, {0}!.
        /// </summary>
        internal static string NavMenu_UserGreeting {
            get {
                return ResourceManager.GetString("NavMenu_UserGreeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TagDefinitions.
        /// </summary>
        internal static string TagDefinitions_Title {
            get {
                return ResourceManager.GetString("TagDefinitions_Title", resourceCulture);
            }
        }
    }
}
